// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/management": {
    params: {};
  };
  "/view-requests": {
    params: {};
  };
  "/leave-request": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/admin" | "/management" | "/view-requests" | "/leave-request" | "/*";
  };
  "../routes/LoginPage.jsx": {
    id: "../routes/LoginPage";
    page: "/";
  } | {
    id: "login";
    page: "/login";
  };
  "../routes/Dashboard.jsx": {
    id: "../routes/Dashboard";
    page: "/dashboard";
  };
  "../routes/AdminPage.jsx": {
    id: "../routes/AdminPage";
    page: "/admin";
  };
  "../routes/ManagementPage.jsx": {
    id: "../routes/ManagementPage";
    page: "/management";
  };
  "../routes/ViewRequests.jsx": {
    id: "../routes/ViewRequests";
    page: "/view-requests";
  };
  "../routes/LeaveRequest.jsx": {
    id: "../routes/LeaveRequest";
    page: "/leave-request";
  };
  "../routes/NotFound.jsx": {
    id: "../routes/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "../routes/LoginPage": unknown;
  "login": unknown;
  "../routes/Dashboard": unknown;
  "../routes/AdminPage": unknown;
  "../routes/ManagementPage": unknown;
  "../routes/ViewRequests": unknown;
  "../routes/LeaveRequest": unknown;
  "../routes/NotFound": unknown;
};